language: php
dist: trusty
sudo: false

php:
  - "7.4"
  - "8.0"
  - "8.1"

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=6.6 WP_MULTISITE=0

matrix:
  include:
    - php: "8.1"
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: "8.0"
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: "7.4"
      env: WP_VERSION=latest WP_MULTISITE=0

branches:
  only:
    - develop
    - /^feature\/.*$/

script:
  - php -v
  - phpunit --version
